
const mongoose = require("mongoose");
const db = require("./models");


mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/mongodb+srv://Project_Admin:Sc**byd00@cluster0.lxp4x.mongodb.net/campaignSchema?retryWrites=true&w=majority"
);

const caseStudySeed = [
    {
        thumbnail: "",
        href: "https://64.media.tumblr.com/cb8458d7cea51b81ae9481f764318805/8f51c83d28e8cb9c-76/s1280x1920/bba78a32c14425dbecdec26fdf176ccc6453b002.jpg&quot",
        name: "Ruby",
        story: "There was once a little girl who was brought up to be a dependent. But one day she started acting like she was in charge of her own life. And it raised doubts and fears in everyone around her. In the people of her town. In her family. And it also raised doubts inside of her. Those doubts are still there. Even with how far I’ve come, the fear is always with me. The fear of falling backwards, all the way back to my home. Sometimes I feel like there is so far to go. Until I’m finally safe. Until I’m free forever. But I’ve come so far. I know that. I’ve been able to impact my family back in Pakistan. Financially, of course. But more importantly I’ve provided an example. Now even the shyest of my female cousins are speaking to me about their dreams. One of my younger sisters is working as a fitness coach. And the other has built her own women’s health company. She’s selling sanitary pads, and is having a huge impact back in Pakistan. But the biggest transformation has been in my mother. She’s been promoted to headmistress of her school, and she’s thinking deeply about child development. She’s opening up computer labs. She’s pushing her female students to learn technology. To create their own space. And to be financially strong. She’s telling them all the things that I needed to hear as a little girl. The road was so lonely for me, and maybe I still carry some unconscious resentment. But my mother has apologized for not supporting me more. And consciously I have forgiven her. Recently she’s become vocal about her own story. She also came from a large family. She was the eldest daughter, and like me she was pressured to get married. She was just a young girl. And she was scared. So she grew into a mother who pushed that fear onto her daughters. And I understand that. She was a product of her time. The internet didn’t exist. There was no window to another world. No example to follow. No woman to show the way. I asked her recently: ‘Did you have dreams when you were young?’ And she said: ‘Don’t go there.’ But I pushed her. I said: ‘Go on, tell me.’ She was quiet for a minute. Then she said: ‘There were so many. But I’ve always wanted to be a pilot."
    },
    {
        thumbnail: "",
        href: "https://www.facebook.com/humansofnewyork/photos/pcb.5369518993122157/5369513619789361/?__cft__[0]=AZWzD5KjxPtPcT5x0RvJv-_eVSvCXIN161it2FmuBP6UlL01Nkd7ZME0JNOG9yqxOR62o_Gt4sKaBCxNIRZEGWpRocp-t_PkE35Rn8JCpZX9HeagOYT9RYSKVhChmlZtDWMEbGRsqFvg5kv8JEsNteyN&__tn__=*bH-R",
        name: "Paula",
        story: "Halfway home I asked to stop for a drink. Then afterward I hopped in the backseat to read a book to my brother. And that’s what saved me. Because the wreck happened a few miles down the road. The entire front of our car was crushed. My first thought was my hands. I had a piano competition coming up, so I looked down at my hands. One of them started to crumble before my eyes. I was taken in an ambulance. My brother was taken in a helicopter. But Dad never regained consciousness. He lived such a big life. His name was Kash. He was an Olympic-caliber skier. He flew jets in the Air Force. But oh man, he was such a good dad. Whenever I was asked to name my best friend—I’d say my dad. That’s how close we were. He died too quickly to salvage his organs. But everything else was donated: his eyes, his tissues, his ligaments. We have a list of fifty people whose lives he changed. The only thing my Mom reserved was his bone. She doesn’t remember why-- but she asked them to set aside some bone. I felt so angry after his death. But in that selfish, teenage way. My life had been so perfect. Now my dad was gone. And I couldn’t even play piano. Piano had been such a huge part of my identity. It was also my stress relief. But all the bones in my left hand were pulverized, and whenever I tried to play with my right, I’d just end up crying. I went through surgery after surgery. Hardware was put in, hardware was taken out, but nothing worked. Finally the doctors told me: ‘Your hand is dying, and the only thing left to try is a bone transplant.’ Only then did my mother remember my father’s bones. When we grafted his bone onto my wrist, the blood started to flow. My hand came back to life. And I could play again. Even now, seventeen years later, and with four kids of my own, piano is such a big part of my life. I play at church. And even though we have a shoebox of a house, we have a piano. In our living room we keep a photo album of my dad. We talk about him all the time: what he did, who he was. I hate that he never got to meet my kids, but they know him. They call him ‘Papa Kash.’ And we know Papa Kash is somewhere else right now. But he’s also very alive in this house."
    },
    {
        thumbnail: "",
        href: "https://scontent.fsyd7-1.fna.fbcdn.net/v/t1.0-9/p960x960/140918573_5360770057330384_700779473586240104_o.jpg?_nc_cat=109&ccb=2&_nc_sid=730e14&_nc_ohc=xAJcDmQL6e8AX9kYQfr&_nc_ht=scontent.fsyd7-1.fna&tp=6&oh=ebf08387d4fd1959a6752827812a7454&oe=60441D5A",
        name: "Belle",
        story: "They opened her up and found nothing but cancer. But even then she didn’t give up. She promised that she wasn’t done fighting. But it became a different kind of fight. It wasn’t easy. She was hooked up to a feeding tube. But she walked so beautifully toward death. She kept a photo album next to her bed. But instead of photos, she kept notecards with Bible verses. She said that her entire life she had thought she loved Jesus. But that now she really loved Jesus. I never once saw her depressed. There were sad moments, but even those were peaceful. And sometimes she’d laugh so hard it would physically hurt. Every day she told me I was beautiful. She’d said it before, but not like this. It was so intentional. And then there were the videos. She recorded videos for the big moments in our lives: graduation, our 21st birthday, our wedding, our first child. Over the years those videos became so precious to me. They’re not very long-- just a few minutes each. She opens each one with a greeting. She’ll congratulate me on the stage of life I just hit. And say how sad she is to not be there. Then she’ll give me some advice. It’s very personalized. She’ll say: ‘I know you struggle with X, Y, and Z, so always remember this.’ Ever since I got married two years ago, I’ve known there was one video left. And it’s always given me comfort-- knowing it was there. So it was bittersweet when my daughter was born on June 27th. My husband and I watched the final video together. It was harder than I expected. She was sicker than the other videos. She spoke really slowly. She talked about how I’d always loved babies, even as a child. And she said that she wished she could be there to cuddle my baby. She talked about my childhood—where I struggled, and where I excelled. And she ended by saying: ‘Love and encourage your babies. They will grow up quickly. So hug them. And pray for them.’ And that was it. She told me that she loved me and said goodbye. For years I’d been dreading that moment. But it felt strangely peaceful. Like I was ready. Ready to take up this role. It’s my turn to have a daughter now. To love her. And to be purposeful with her, just like my mom was purposeful with me."
    }
]

db.CaseStudy.remove({})
    .then(() => db.campaignSchema.CaseStudy.insertMany(caseStudySeed))
    .then(data => {
        console.log(data.result.n + " records inserted!");
        process.exit(0);
    })
    .catch(err => {
        console.error(err);
        process.exit(1);
    });