
const mongoose = require("mongoose");
const db = require("../models");


mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/reactrecipes"
);

const caseStudySeed = [
    {
        thumbnail: "",
        href: "https://64.media.tumblr.com/cb8458d7cea51b81ae9481f764318805/8f51c83d28e8cb9c-76/s1280x1920/bba78a32c14425dbecdec26fdf176ccc6453b002.jpg&quot",
        name: "Ruby Atom",
        story: "There was once a little girl who was brought up to be a dependent. But one day she started acting like she was in charge of her own life. And it raised doubts and fears in everyone around her. In the people of her town. In her family. And it also raised doubts inside of her. Those doubts are still there. Even with how far I’ve come, the fear is always with me. The fear of falling backwards, all the way back to my home. Sometimes I feel like there is so far to go. Until I’m finally safe. Until I’m free forever. But I’ve come so far. I know that. I’ve been able to impact my family back in Pakistan. Financially, of course. But more importantly I’ve provided an example. Now even the shyest of my female cousins are speaking to me about their dreams. One of my younger sisters is working as a fitness coach. And the other has built her own women’s health company. She’s selling sanitary pads, and is having a huge impact back in Pakistan. But the biggest transformation has been in my mother. She’s been promoted to headmistress of her school, and she’s thinking deeply about child development. She’s opening up computer labs. She’s pushing her female students to learn technology. To create their own space. And to be financially strong. She’s telling them all the things that I needed to hear as a little girl. The road was so lonely for me, and maybe I still carry some unconscious resentment. But my mother has apologized for not supporting me more. And consciously I have forgiven her. Recently she’s become vocal about her own story. She also came from a large family. She was the eldest daughter, and like me she was pressured to get married. She was just a young girl. And she was scared. So she grew into a mother who pushed that fear onto her daughters. And I understand that. She was a product of her time. The internet didn’t exist. There was no window to another world. No example to follow. No woman to show the way. I asked her recently: ‘Did you have dreams when you were young?’ And she said: ‘Don’t go there.’ But I pushed her. I said: ‘Go on, tell me.’ She was quiet for a minute. Then she said: ‘There were so many. But I’ve always wanted to be a pilot."
    },
    {
        thumbnail: "",
        href: "http://www.recipezaar.com/Baked-Turkey-Sausage-Penne-327796",
        name: "Ruby Atom",
        story: "There was once a little girl who was brought up to be a dependent. But one day she started acting like she was in charge of her own life. And it raised doubts and fears in everyone around her. In the people of her town. In her family. And it also raised doubts inside of her. Those doubts are still there. Even with how far I’ve come, the fear is always with me. The fear of falling backwards, all the way back to my home. Sometimes I feel like there is so far to go. Until I’m finally safe. Until I’m free forever. But I’ve come so far. I know that. I’ve been able to impact my family back in Pakistan. Financially, of course. But more importantly I’ve provided an example. Now even the shyest of my female cousins are speaking to me about their dreams. One of my younger sisters is working as a fitness coach. And the other has built her own women’s health company. She’s selling sanitary pads, and is having a huge impact back in Pakistan. But the biggest transformation has been in my mother. She’s been promoted to headmistress of her school, and she’s thinking deeply about child development. She’s opening up computer labs. She’s pushing her female students to learn technology. To create their own space. And to be financially strong. She’s telling them all the things that I needed to hear as a little girl. The road was so lonely for me, and maybe I still carry some unconscious resentment. But my mother has apologized for not supporting me more. And consciously I have forgiven her. Recently she’s become vocal about her own story. She also came from a large family. She was the eldest daughter, and like me she was pressured to get married. She was just a young girl. And she was scared. So she grew into a mother who pushed that fear onto her daughters. And I understand that. She was a product of her time. The internet didn’t exist. There was no window to another world. No example to follow. No woman to show the way. I asked her recently: ‘Did you have dreams when you were young?’ And she said: ‘Don’t go there.’ But I pushed her. I said: ‘Go on, tell me.’ She was quiet for a minute. Then she said: ‘There were so many. But I’ve always wanted to be a pilot."
    }
]